# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package and TypeScript config
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install dependencies, build and remove devDependencies
RUN npm install && npm run build && npm prune --production

# Default command
ENTRYPOINT ["node", "build/index.js"]
